### ISSUE TITLE
Error indexing my custom Engine

### ISSUE THREAD

**Issue by godwinwaswa** [VincentFoulon80/php-search#5]
**Describe the bug**
I get this error after parsing my custom config array to Engine() instance and try to update the indexes.

Warning: require_once(RemoveAccentsTokenizer.php): failed to open stream: No such file or directory in /storage/emulated/0/htdocs/RealDriss/tools/Objects/autoload.php on line 3

Fatal error: require_once(): Failed opening required 'RemoveAccentsTokenizer.php' (include_path='.:/usr/local/lib/php') in /storage/emulated/0/htdocs/RealDriss/tools/Objects/autoload.php on line 3

**To Reproduce**
The issue must be with the object,because my autoloader is okay,it works with other objects flawlessly.

**Expected behavior**
It should not throw an error,because there is no error thrown while using the default configuration 

**Additional context**

**Comment by VincentFoulon80** [comment]
Hello ! 
First can you check if your use statement is correct (should be VFou\Search\Tokenizers\RemoveAccentTokenizer).
If that's correct, try to check if the file actually exists (vendor/vfou/php-search/Tokenizers/RemoveAccentTokenizer.php).
If the file exists, try to regenerate composer's autoload file with the "composer dumpautoload" command.
Else can you check your composer.json file and tell me what version of the library is used, please ?

Thanks in advance !

**Comment by godwinwaswa** [comment]
> Hello !
> First can you check if your use statement is correct (should be VFou\Search\Tokenizers\RemoveAccentTokenizer).
> If that's correct, try to check if the file actually exists (vendor/vfou/php-search/Tokenizers/RemoveAccentTokenizer.php).
> If the file exists, try to regenerate composer's autoload file with the "composer dumpautoload" command.
> Else can you check your composer.json file and tell me what version of the library is used, please ?
> 
> Thanks in advance !

Thanks it finally worked,I just had to include all the use statements as they are in my admin panel file,the file for adding new document entries,basically every file I have to generate henceforth,for which depends on any of my custom engine configuration.

**Comment by VincentFoulon80** [comment]
Glad you managed to get it to work ! 🙂
If your configuration is identical at multiple places you can store it in a single file/class as a const (or in a function if you need to use variables) and use it at each initialization.

Do you mind if I close this issue ?
